"""seller reviews

Revision ID: 02eec2989f9c
Revises: 75e197ddadba
Create Date: 2026-07-14 18:48:07.261614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02eec2989f9c"
down_revision: str | Sequence[str] | None = "75e197ddadba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seller_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.String(length=128), nullable=False),
        sa.Column("buyer_id", sa.String(length=128), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_seller_reviews_buyer_id"), "seller_reviews", ["buyer_id"], unique=False
    )
    op.add_column(
        "buyer_profiles",
        sa.Column("rating_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "buyer_profiles",
        sa.Column("rating_sum", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###
    with op.batch_alter_table("adjustments") as batch_op:
        batch_op.create_check_constraint("ck_adjustments_amount_nonneg", "amount >= 0")


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("adjustments") as batch_op:
        batch_op.drop_constraint("ck_adjustments_amount_nonneg", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buyer_profiles", "rating_sum")
    op.drop_column("buyer_profiles", "rating_count")
    op.drop_index(op.f("ix_seller_reviews_buyer_id"), table_name="seller_reviews")
    op.drop_table("seller_reviews")
    # ### end Alembic commands ###
