"""moderation

Revision ID: 48d2c1099dea
Revises: 02eec2989f9c
Create Date: 2026-07-14 20:21:05.116351

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48d2c1099dea"
down_revision: str | Sequence[str] | None = "02eec2989f9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.String(length=128), nullable=False),
        sa.Column(
            "target_kind",
            sa.Enum(
                "user",
                "review",
                "seller_review",
                name="reporttargetkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "actioned", "dismissed", name="reportstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("resolution_note", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reporter_id", "target_kind", "target_id"),
    )
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.add_column(
        "reviews",
        sa.Column("comment_hidden", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "seller_reviews",
        sa.Column("comment_hidden", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="userstatus", native_enum=False, length=32),
            nullable=False,
            server_default="active",
        ),
    )
    op.add_column("users", sa.Column("suspended_reason", sa.String(length=2000), nullable=True))
    op.add_column("users", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_column("users", "suspended_at")
    op.drop_column("users", "suspended_reason")
    op.drop_column("users", "status")
    op.drop_column("seller_reviews", "comment_hidden")
    op.drop_column("reviews", "comment_hidden")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
