"""disputes

Revision ID: 75e197ddadba
Revises: b215d30cb3d9
Create Date: 2026-07-14 09:17:44.686519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e197ddadba'
down_revision: Union[str, Sequence[str], None] = 'b215d30cb3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('buyer', 'provider', name='disputesource', native_enum=False, length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'chargeback_won', 'chargeback_lost', name='disputestatus', native_enum=False, length=32), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('clawback_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resolution_note', sa.String(length=2000), nullable=True),
    sa.Column('provider_dispute_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_disputes_buyer_id'), 'disputes', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_disputes_provider_dispute_id'), 'disputes', ['provider_dispute_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('refund', 'clawback', 'chargeback_loss', 'chargeback_fee', name='adjustmentkind', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_ref', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_dispute_id'), 'adjustments', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_adjustments_job_id'), 'adjustments', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustments_job_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_dispute_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_provider_dispute_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_buyer_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
