"""initial schema

Revision ID: c7807e909e5f
Revises: 
Create Date: 2026-07-11 22:51:34.339082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7807e909e5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('service_type_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=True),
    sa.Column('seller_payout', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'completed', 'expired', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_buyer_id'), 'jobs', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_jobs_seller_id'), 'jobs', ['seller_id'], unique=False)
    op.create_index(op.f('ix_jobs_service_type_id'), 'jobs', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('platform_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margin_absolute', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ceiling_multiplier', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('matching_strategy', sa.String(length=64), nullable=False),
    sa.Column('adjuster_params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('service_type_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_buyer_id'), 'quotes', ['buyer_id'], unique=False)
    op.create_table('seller_profiles',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_types',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('base_buyer_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_seller_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=False),
    sa.Column('service_type_id', sa.String(length=128), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'service_type_id')
    )
    op.create_index(op.f('ix_availability_seller_id'), 'availability', ['seller_id'], unique=False)
    op.create_index(op.f('ix_availability_service_type_id'), 'availability', ['service_type_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('service_type_id', sa.String(length=128), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=False),
    sa.Column('seller_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('offered', 'accepted', 'declined', 'expired', name='offerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_job_id'), 'offers', ['job_id'], unique=False)
    op.create_index(op.f('ix_offers_seller_id'), 'offers', ['seller_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('pipelines',
    sa.Column('service_type_id', sa.String(length=128), nullable=False),
    sa.Column('buyer', sa.JSON(), nullable=False),
    sa.Column('seller', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('service_type_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_reviews_seller_id'), 'reviews', ['seller_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seller_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reviews_seller_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_seller_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_job_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_availability_service_type_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_seller_id'), table_name='availability')
    op.drop_table('availability')
    op.drop_table('service_types')
    op.drop_table('seller_profiles')
    op.drop_index(op.f('ix_quotes_buyer_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_service_type_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_seller_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_buyer_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
